export default {
  extends: ['stylelint-config-standard', 'stylelint-config-standard-vue'],
  plugins: ['stylelint-order'],
  ignoreFiles: [
    'dist/**',
    'dist-pages/**',
    'node_modules/**',
    'playwright-report/**',
    'test-results/**',
    'coverage/**',
  ],
  rules: {
    'color-hex-length': 'long',
    'media-feature-range-notation': 'prefix',
    'order/properties-order': [
      [
        'content',
        'position',
        'inset',
        'top',
        'right',
        'bottom',
        'left',
        'z-index',
        'display',
        'grid-template',
        'grid-template-columns',
        'grid-template-rows',
        'grid-column',
        'grid-row',
        'place-items',
        'align-items',
        'align-self',
        'justify-content',
        'justify-self',
        'gap',
        'order',
        'flex',
        'flex-direction',
        'flex-wrap',
        'width',
        'min-width',
        'max-width',
        'height',
        'min-height',
        'max-height',
        'box-sizing',
        'margin',
        'border',
        'border-color',
        'border-radius',
        'padding',
        'overflow',
        'overflow-x',
        'overflow-y',
        'color',
        'font',
        'font-family',
        'font-size',
        'font-weight',
        'line-height',
        'text-align',
        'text-decoration',
        'text-overflow',
        'white-space',
        'overflow-wrap',
        'background',
        'background-color',
        'box-shadow',
        'opacity',
        'cursor',
        'appearance',
        'pointer-events',
        'transition',
        'transform',
        'scroll-margin-top',
      ],
      {
        unspecified: 'bottomAlphabetical',
      },
    ],
    'selector-class-pattern': null,
  },
};
